#pragma once
#include "constants.h"
// #define DEBUG
// #define DEBUG_VERBOSE
// #define DEBUG_OFFLINE

#define DEFAULT_IDE_SHUTDOWN TEN_MINUTES
#define DEFAULT_IDE_ACTIVE 100
#define DEFAULT_IDE_PAUSE 250
#define DEFAULT_FLP_ACTIVATING 500
#define DEFAULT_FLP_DEACTIVATING 750

#define DEFAULT_VOLUME 15
#define DEFAULT_ANSI false
#define DEFAULT_PROFILE 0