#pragma once
#define DEFAULT_VOLUME 15
#define DEFAULT_ANSI false
#define DEFAULT_PROFILE 0

#define IDLE_THRESHOLD 100
#define ONE_MINUTE 60000L
#define TEN_MINUTES 600000L
#define FIFTEEN_MINUTES 900000L
#define SHUTDOWN_THRESHOLD TEN_MINUTES